becks-boo/handy_bee_app

app/models/user.rb, db/migrate/20210213132452_add_details_to_users.rb, db/schema.rb
I did an add-migration and added a few attributes to the user and added the associations.
=> update user table and associations

app/models/business.rb
Just fixed the typo in business model validates "presence: true".
=> fix typo in validation (true)

app/controllers/application_controller.rb, app/models/user.rb, app/views/devise/registrations/new.html.erb
Added the attributes role (with collection of contractor and customer) and user_name to the user sign-up form. Added validations presence true for user_name and role in user.rb.
=> update user sign up form and add validation

Gemfile, Gemfile.lock, app/controllers/application_controller.rb, app/controllers/bookings_controller.rb, app/policies/application_policy.rb, app/policies/booking_policy.rb, db/schema.rb, test/policies/booking_policy_test.rb
Installed pundit gem and created application_policy.rb file. Updated application_controller. Created booking_policy.rb file. Authorized booking new and create method if user.role == "Contractor". 
Other than that, there aren't many methods to authorize, maybe index?
=> Pundit branch

app/models/booking.rb, app/models/business.rb, app/models/chatroom.rb, app/models/message.rb, app/models/review.rb, app/models/user.rb, app/views/bookings/new.html.erb, db/migrate/20210219174414_create_reviews.rb, db/migrate/20210219180246_create_chatrooms.rb, db/migrate/20210219180328_create_messages.rb, db/migrate/20210219181036_add_user_ref_to_bookings.rb, db/schema.rb, test/models/chatroom_test.rb, test/models/message_test.rb, test/models/review_test.rb
Created all the models (review, chatroom and messages) and all the associations. No controllers yet. Let's discuss the reviews, if it should be a <has_many through> association. 
Added user references in bookings. 
Also improved booking new form.
=> Bug fix db

app/models/booking.rb, app/models/business.rb, app/models/review.rb, app/models/user.rb, db/migrate/20210220104632_remove_qualifications_from_users.rb, db/migrate/20210220104847_remove_address_from_users.rb, db/migrate/20210220132455_add_columns_to_business.rb, db/migrate/20210220134131_change_confirmed_default.rb, db/schema.rb
First added missing associations to review. Then I removed and added the columns on different tables. Then did the validations.
=> Associations validations

db/schema.rb, db/seeds.rb
Fixed the seed bug, seed was using old attributes.
=> fixed seed bug, caused by wrong and missing attributes

app/views/devise/registrations/new.html.erb, app/views/pages/account.html.erb, app/views/shared/forms/_contractor_form.html.erb
Created app/views/shared/forms folder with partial of customer and contractor form rendering to registration new.html.erb.
=> Partial for forms

app/controllers/businesses_controller.rb, app/policies/business_policy.rb, app/views/businesses/new.html.erb, app/views/businesses/show.html.erb
Business has index, show, new and create method. Add language, location and description to the show page. Want to do multiple selection when creating a business for that need to merge and work on another branch.
=> Other business methods

app/assets/stylesheets/pages/_home.scss
I changed the font color on "Choose a service" to black when u hover on it. If we dont like we can change it :)
=> hover black font dropdown

app/assets/stylesheets/components/_avatar.scss, app/views/devise/registrations/edit.html.erb, app/views/devise/registrations/new.html.erb, app/views/pages/account.html.erb, app/views/shared/_navbar.html.erb
=> User photo and avatar

app/assets/stylesheets/pages/_show.scss, app/views/businesses/show.html.erb
=> style work on show page

app/assets/stylesheets/pages/_index_businesses.scss
should be fine now, please let me know if not
=> margin cards

app/views/businesses/index.html.erb, app/views/businesses/show.html.erb
Added avatar to business index and show page
=> add avatar to index business card and show business page

app/controllers/businesses_controller.rb, app/policies/business_policy.rb, app/views/businesses/edit.html.erb, app/views/businesses/show.html.erb
Added edit, update and destroy methods for business. After destroy redirect_to account page. Added policies for business.
=> Missing business methods

app/assets/stylesheets/pages/_show.scss, app/views/businesses/show.html.erb
=> Show page one business new style

app/controllers/businesses_controller.rb, app/models/business.rb, app/models/user.rb, app/views/businesses/index.html.erb, app/views/businesses/new.html.erb, app/views/businesses/show.html.erb, db/seeds.rb
Added business_language to seed and global variable for category in business model. Update user model with dependent destroy.
=> Fix seed language

app/controllers/businesses_controller.rb, app/views/business_languages/new.html.erb, app/views/businesses/new.html.erb
Now there is only one form for creating a business. No gem, no yarn and no second form needed. 
Business_languages view deleted.
=> Fix one form

app/assets/stylesheets/pages/_show.scss, app/views/businesses/show.html.erb
=> Business showpage pics layout

app/javascript/components/review_carousel.js, app/views/businesses/show.html.erb
Now review carousel is back in the page
=> add missing review_carousel.js and the code to show page

app/javascript/components/review_carousel.js, app/views/reviews/_review_carousel.html.erb
Changed row to d-flex class in carousel-inner. Also deleted a forgotten console.log in the function.
=> fix out of line fourth of review

app/views/shared/_navbar.html.erb
allow to change acconut picture
=> add edit account button to my account page

app/views/businesses/index.html.erb, test/fixtures/users.yml, test/models/user_test.rb, test/system/businesses_test.rb
unit test tests is user.user_name matches username when created. System test test what the user sees when going to index businesses page
=> write first unit and system test

app/controllers/businesses_controller.rb, app/controllers/pages_controller.rb, app/views/pages/home.html.erb
I included the associated modesl in the root page and business index page to reduce query time
=> address n+1 queris

app/assets/stylesheets/components/_form.scss, app/assets/stylesheets/components/_index.scss, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/devise/shared/_links.html.erb
Restyled the sign in and sign up form. Sign up not 100% finished.
=> Sign up login page beautify

app/javascript/components/toggle_sign_up.js, app/views/devise/registrations/new.html.erb
Just add a comment on JS function that is not used anymore and deleted an id in the form also not used.
=> comment to js function and delete id from form

app/javascript/packs/application.js, app/views/shared/_navbar.html.erb
Turbolinks was causing the bug in logo and btn, disabled turbolinks for this specific btn.
=> disabled turbolinks for logo btn

app/assets/stylesheets/components/_form.scss, app/views/businesses/edit.html.erb, app/views/businesses/new.html.erb, app/views/devise/registrations/new.html.erb
Restyled simple form for to match the style of sign-in and sign-up form.
=> Improve forms
